vcf: "/gpfs/project/projects/medbioinf/users/ebler/haplotype-sampling/companion-paper/hprc2-companion-paper/genotyping-pipeline/results-hprc2-full/genotyping/pangenie_all-samples_unfiltered.vcf.gz"
chain: "chm13v2-grch38.chain.gz"
reference: "/gpfs/project/projects/medbioinf/users/ebler/haplotype-sampling/companion-paper/data/chm13v2.0_maskedY_rCRS.fa"
target_reference: "1KG_ONT_VIENNA_hg38.fa"
outname: "HPRC2-PG-1kGP-unfiltered"
